version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8-browsers

        steps:
            - checkout
            - run:
                name: Create .npmrc
                command: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: Install dependencies
                command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                    - ./node_modules
            - run:
                name: Add hostname
                command: echo 127.0.0.1 local.ecosia.org | sudo tee -a /etc/hosts
            - run:
                name: Run tests
                command: npm test
            - deploy:
                name: Deploy
                command: |
                    if [ "${CIRCLE_BRANCH}" == "main" ]; then
                        git config --global user.email "dev@ecosia.org"
                        git config --global user.name "Ecosia automated deployment"
                        npm publish
                        git tag "v`node -p -e \"require('./package.json').version\"`"
                        git push origin $CIRCLE_BRANCH --tags
                    fi
